theme = "hugo-geo"
themesdir = "themes"
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "alexurquhart@gmail.com"

	profilepic = "img/profilePhoto.jpg"
	
	title = "Miguel Angel Cortes"
	subtitle = "Miguel Cortes"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/Macn1234"
	[[params.socialbuttons]]
	faicon = "facebook"
	url = "https://www.facebook.com/miguel.cortes.3762"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com"
	[[params.socialbuttons]]
	faicon = "google-plus"
	url = "https://plus.google.com/u/0/117144648886294691970"

	[[params.navlinks]]
	name = "Sobre mi"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Proyectos"
	url = "tutorial/"
